<?php // ------- yBlog Page Variables -----------------------//
	$TITLE 		= "Site Setup"; 	//default=SITE_NAME
	$DESC			= "Required and optional configuration";//default=SITE_DESC
	$AVATAR		= "img/cmsArch.jpg";			//default=SITE_LOGO
	$MENU_ORDER	= 5;					 	//default=1,0 = not menued
//	$AUTHOR		= "Author";			 	//default=SITE_AUTHOR
//	$STYLES		= "elegant");			//blue(default), none, box, elegant
include_once '../lib/yBlog.php';
//-----------------------------------------------------------//?>
<h2>Content Directories</h2>
<?php dates('Nov 2020', 'July 7, 2021', 'Beta .33: July 7, 2021') ?>
<p>Content pages may be in the root directory and any directory besides the yBlog directories. 
By convention, image files are kept in an <i>./img/</i> subdirectory in the same directory as 
the content files. PDF files and ZIP files for download must be in the <i>SITE_ROOT/inc/</i> 
directory for the plugins to work. </p>
<h2>yBlog Directories</h2>
<p>Content pages are in the root directory any desired folders except those reserved for yBlog, LIB, and INC. 
There are a few more support files in the root directory:</p>
<ul><li><i>./htaccess</i> will probably work on your ISP's server with minor 
customizations (see comments in file):
<br><br>
<?php codeBegin(); 
echo htmlspecialchars(file_get_contents('../.htaccess')); 
codeEnd(250,'clike',); ?>
</li><li><i>./robots.txt</i> is written so it needs no updating. 
</li><li><i>./favicons.ico</i> may be replaced to change the icon shown in the browser toolbar 
</li><li><i>./sitemap.xml</i> may be automatically updated in a future release.  
</li><li><i>./img/</i> is the suggested location for content's image files.  
</li><li><i>./inc/</i> contains downloadable files and PDFs.  
</li></ul>
<h2>yBlog Directories</h2>
<ul><li><i>./lib/</i> contains the site template and CMS PHP files, described below.  
</li><li><i>./lib/img</i> contains the template's image files.  
</li><li><i>./lib/CodeMirror/</i> contains the code editor.  
</li><li><i>./lib/img/</i> contains image files for the template.  
</li><li><i>./lib/pwd/</i> contains protectedd login data.  
</li></ul>

<h2>The <i>yBlog.php</i> File</h2>
<p>In the page template, the <code>REQUIRE_ONCE&nbsp;./lib/yBlog.php</code> statement 
calls the maikn script to generate the page head, nav bar, responsive body header, TOC, 
plugin insertion, and footer. This file need not be edited, but you can change the 
top-of-page layout and other such features in this file. </p>

<h2>The <i>config.php</i> File</h2>
<p><li>The <i>./lib/yBlog.php</i> file first calls a small site variable file, <i>./lib/config.php</i>. 
The <i>./lib/config.php</i> file sets the site's name, base URL, and options. This file then generates  
one set of variables for the public server, and another for localhost at http://127.0.0.1 
which is selected automatically, depending where the directory resides. This file also sets site options, such 
as the logo, default stylesheet, and ID's for Google and Adobe integration. Additionally it provides
default page values for any variables not set on individual content pages.</p>
<?php codeBegin(); 
	echo htmlspecialchars(file_get_contents('../lib/config.php'));
codeEnd(250); ?>

<blockquote><p><i>Specifications for the variables are in preparation</i></p></blockquote>

<ul><li>To set up <a href= "https://analytics.withgoogle.com/">Google Analytics</a>, visit 
its site and obtain an ID for this config file.
</li><li>To set up <a href= "https://documentcloud.adobe.com/view-sdk-demo/index.html#/view/FULL_WINDOW/Bodea%20Brochure.pdf">
Adobe DC Reader</a>, visit its site and obtain an ID for this config file.
</li><ul>
<p>The <i>./lib/yBlog.php</i> file then generates all the metadata for the page's HEAD element 
from the page and site variables. It also includes the site stylesheet 
 and all  scripts needed for Google Analytics and plugins. </p>
<p>The <i>./lib/yBlog.php</i> file then closes the HEAD element and adds an opening &lt;BODY> tag.
At the top of the BODY element, yBlog inserts a HEADER element which contains the responsive header. 
A NAV element inside the HEADER element containing the site menu. The menu contents 
generated automatically. </p>
<p>The <i>./lib/head.php</i> file then parses the page and replaces the PHP plugin snippets with 
HTML andJavaScript, generated by the <i>./lib/plugins.php</i> file.</p> 

<h2>The <i>foot.php</i> File</h2>
<p>After an article's content, the <i>./lib/yBlog.php</i> file adds footer content from the 
<i>./lib/foot.php</i>file. Each blog site will prefer a different footer, which is edited just 
like a standard Web page. The <i>.lib/yBlog.php file</i> then performs 
any necessary parsing on the whole page and sends it to the browser client.</p>